version: '3'

services:
  db:
    image: postgres:9.6
    env_file:
      - .env
    volumes:
      - ~/mentorcoin/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
     - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
