# Generated by Django 2.0 on 2018-02-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_url', models.URLField()),
                ('github_username', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=18)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
