# Generated by Django 2.0 on 2018-02-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorcoin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codereview',
            name='pr_title',
            field=models.CharField(default='Default Title', max_length=100),
        ),
    ]
