# Generated by Django 2.0 on 2018-02-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorcoin_app', '0002_codereview_pr_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='codereview',
            name='experience_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert')], default='Beginner', max_length=36),
        ),
        migrations.AddField(
            model_name='codereview',
            name='expires',
            field=models.IntegerField(choices=[(259200, '3 Days'), (604800, '1 Week'), (2592000, '1 Month'), (9999999999, 'Never')], default=2592000),
        ),
        migrations.AddField(
            model_name='codereview',
            name='full_name',
            field=models.CharField(default='na', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codereview',
            name='keywords',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='codereview',
            name='project_length',
            field=models.CharField(choices=[('Hours', 'Hours'), ('Days', 'Days'), ('Weeks', 'Weeks')], default='Hours', max_length=24),
        ),
        migrations.AlterField(
            model_name='codereview',
            name='pr_title',
            field=models.CharField(max_length=100),
        ),
    ]
