# Generated by Django 2.0 on 2018-02-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorcoin_app', '0004_codereview_notification_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codereview',
            name='amount',
            field=models.DecimalField(decimal_places=18, max_digits=100),
        ),
    ]
