# Generated by Django 2.0 on 2018-02-18 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorcoin_app', '0005_auto_20180217_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codereview',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=9),
        ),
    ]
