# Generated by Django 2.0 on 2018-02-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorcoin_app', '0006_auto_20180217_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='codereview',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('claimed', 'claimed'), ('closed', 'closed')], default='open', max_length=12),
        ),
    ]
