# Generated by Django 2.0 on 2018-02-18 02:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentorcoin_app', '0007_codereview_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='codereview',
            name='claimed_user',
            field=models.ForeignKey(null=True, on_delete=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
