# Generated by Django 2.0 on 2018-02-18 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mentorcoin_app', '0008_codereview_claimed_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codereview',
            name='claimed_user',
        ),
        migrations.RemoveField(
            model_name='codereview',
            name='github_username',
        ),
        migrations.AddField(
            model_name='codereview',
            name='claimed_by',
            field=models.ForeignKey(null=True, on_delete=None, related_name='code_reviews_claimed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codereview',
            name='submitted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='code_reviews_submitted', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
