# Generated by Django 2.0 on 2018-02-18 04:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mentorcoin_app', '0009_auto_20180217_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codereview',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='codereview',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codereview',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('claimed', 'claimed'), ('fulfilled', 'fulfilled'), ('closed', 'closed')], default='open', max_length=12),
        ),
    ]
